### ISSUE TITLE
Initiating App installation

### ISSUE THREAD

**Issue by Tall-Paul** [PrimePenguin/PrimePenguin.WixSharp#5]
Hi, do you have any examples of using this library to initiate app installation?  

So my use case / workflow is:

User is on my website, clicks 'connect', I want to then start the installation of my app into their wix site.

**Comment by Khungersumit** [comment]
Hi @Tall-Paul

**Comment by Khungersumit** [comment]
> Hi, do you have any examples of using this library to initiate app installation?
> 
> So my use case / workflow is:
> 
> User is on my website, clicks 'connect', I want to then start the installation of my app into their wix site.

Hi @Tall-Paul 

**Prerequisite for Installation** 
1). AppId
2). AppSecret (You will get both these in your's app dashboard OAuth Section)
3). You must have defined a redirect URL in the same OAuth section It should look like (https://XYZ/api/services/app/Wix/InstallWix), at this URL they will send you an authorization code. You will need this authorization code to get AccessToken and RefreshToken.

**Installation Process**
When the user clicks on the connect button, he must be redirected along with redirect Url at the WIX Server 
IT should look like the following

https://www.wix.com/app-oauth-installation/consent?appId={your_app_id}&redirectUrl=https://XYZapi//InstallWix&state={your_state_data|optional}

In return, they will give you an authorization code at the same redirect Url which you sent (Please make sure this redirect Url is also listed at your App OAuth Dashboard Step 3 of Prerequisite). 

Using this authorization code along with AppId and App SecretKey you need to authorize it.
(You can use our library code to get AccessToken and RefreshToken, 
you can save this refresh token to generate new access token again as access token expires in 10 minutes). 
```cs
AuthorizationService.Authorize(authorization code, YOUR_APP_KEY, YOUR_APP_KEY-SECRET)
```

Now you have got access token, you can use our library to query for products, order and many more.
