### ISSUE TITLE
Question: How to get variants with products?

### ISSUE THREAD

**Issue by Tall-Paul** [PrimePenguin/PrimePenguin.WixSharp#7]
Hi, I'm currently doing this to get all products from my store:

 var productService = new WixSharp.Services.Product.ProductService(config.AccessToken);
 var query = new WixSharp.Entities.ProductRootQuery();            
 var products = await productService.GetProductsAsync(query);

However, that doesn't provide any variant data, I presume because I need to provide a flag in the query?

**Comment by ajayak** [comment]
Hi @Tall-Paul,

Wix does not provide variants information in Products API
https://dev.wix.com/api/wix-stores#catalog.collection.get-collection

You need to make another request to get variant data
```cs
var productResponse = new ProductService(args.AccessToken);
var productVariants = await productResponse.GetQueryProductVariantsAsync(product.Id);
```

**Comment by Tall-Paul** [comment]
See: https://dev.wix.com/api/wix-stores#catalog.product.query-products

"Product variants, will be provided if the the request was sent with the includeVariants flag"

**Comment by ajayak** [comment]
@Tall-Paul, Thanks!
@Khungersumit did some changes in the sdk recently for this 😄 

In your above code, just set `IncludeVariants` to `true` as shown below:

```cs
var productService = new WixSharp.Services.Product.ProductService(config.AccessToken);
var query = new WixSharp.Entities.ProductRootQuery();
query.IncludeVariants = true;
var products = await productService.GetProductsAsync(query);
```

**Comment by Tall-Paul** [comment]
Okay, that gets me the Variants, however (for some stupid reason) Wix don't provide the inventory levels for those variants in that data.

What I want to do is make a request for all inventory data for this store, so I can cache it locally and then loop through my products / variants updating their stock level.

However if I do this:

```
 var InventoryService = new WixSharp.Services.InventoryItem.InventoryItemService(config.AccessToken);
var query2 = new WixSharp.Entities.QueryInventoryRequest();
query2.Query = new WixSharp.Entities.Query();
var dat = await InventoryService.QueryInventory(query2);
```

I get the following error

Could not convert string to integer: 1578653962536190. Path 'inventoryItems[0].numericId'.

Am I doing something obviously wrong here?

**Comment by Tall-Paul** [comment]
fixed in #8 

The Numeric Id in Entity.Product was already a string, so I changed the ones elsewhere from an int (too small for the Wix IDs) to a string.

**Comment by ajayak** [comment]
Thanks for the PR @Tall-Paul 👍

**Comment by ajayak** [comment]
> Okay, that gets me the Variants, however (for some stupid reason) Wix don't provide the inventory levels for those variants in that data.
> 
> What I want to do is make a request for all inventory data for this store, so I can cache it locally and then loop through my products / variants updating their stock level.
> 
> However if I do this:
> 
> ```
>  var InventoryService = new WixSharp.Services.InventoryItem.InventoryItemService(config.AccessToken);
> var query2 = new WixSharp.Entities.QueryInventoryRequest();
> query2.Query = new WixSharp.Entities.Query();
> var dat = await InventoryService.QueryInventory(query2);
> ```
> 
> I get the following error
> 
> Could not convert string to integer: 1578653962536190. Path 'inventoryItems[0].numericId'.
> 
> Am I doing something obviously wrong here?

I guess string is better choice for this as it exceeds `int` limit. Maybe someday, it may exceed `long` limit. Never know 😆
