### ISSUE TITLE
Question Bookings Schedules and Partcipants

### ISSUE THREAD

**Issue by davidbuckleyni** [PrimePenguin/PrimePenguin.WixSharp#9]
I have a projecting requiring me to import bookings schedules and participants from their booking platform.

Can i use your library to achieve that?

**Comment by ajayak** [comment]
Sorry @davidbuckleyni. that is not supported in this SDK. 
You may extend this SDK to achieve it and use it as base

**Comment by davidbuckleyni** [comment]
Wix support are dread full do u no how to make api calls to their oauth getting a perm token seems to be half the battle.

**Comment by ajayak** [comment]
You can use this sdk and create a service as we did here:
https://github.com/PrimePenguin/PrimePenguin.WixSharp/blob/master/WixSharp/Services/Order/OrderService.cs

Then make calls using your service. First complete the oAuth flow and get an accessToken.
Example: `var service = new OrderService(shopAccessToken);`

**Comment by ajayak** [comment]
To get token, create a new app either private works fine.
Setup required permissions, oauth redirect uri etc.
From your page, redirect to oauth page of app and capture code. Generate access token with the code.

Example:
```cs
            var authorizationResponse = await AuthorizationService.Authorize(authorizationCode, appId, appSecretKey);
            var accessToken = authorizationResponse.AccessToken;

            var appInstanceService = new AppInstanceService(accessToken);
            var appInfo = await appInstanceService.GetAsync();
            var siteName = appInfo.Site.SiteDisplayName;
```

**Comment by davidbuckleyni** [comment]
Their  document speaks about how u must have a component on the web site to access the api is that nessary? I have the app id and the secret id but i cant find the authorization code how do i get that?

**Comment by davidbuckleyni** [comment]
Sorry am not used to wix apps so not a clue where to start for my client

**Comment by davidbuckleyni** [comment]
Would their be any way to chat about this with u maybe over a teams call some point would be greatfull on the connection process.

**Comment by davidbuckleyni** [comment]
I believe the token given only last 5 mins do we have to re auth every call?

**Comment by ajayak** [comment]
@davidbuckleyni sharing our app code as an example of how to handle this:
```cs
public async Task<string> GetAccessToken(int scId)
{
    var sc = await _scRepository.GetAll().IgnoreQueryFilters()
        .FirstOrDefaultAsync(c => c.Id == scId);
    if (IsExistingTokenValid(sc)) return sc.AccessToken;

    var authResult = await AuthorizationService.GetAccessToken(appId, appSecretKey, refreshToken);
    sc.AccessToken = authResult.AccessToken;
    sc.KeyId = authResult.RefreshToken;
    sc.TTL = 540;  // 9*60 access token will be alive for 9 minutes (540 seconds)
    sc.LastModificationTime = DateTime.Now;
    await _scRepository.UpdateAsync(sc);
    return authResult.AccessToken;
}

private bool IsExistingTokenValid(UserSc sc)
{
    return sc.LastModificationTime.HasValue &&
           DateTime.Now.AddMinutes(9) <
           sc.LastModificationTime.Value.AddSeconds(sc.TTL.GetValueOrDefault());
}
```
